# fly.toml app configuration file generated for chh-team3-bclc on 2023-11-28T12:34:49+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "chh-team3-bclc"
primary_region = "sin"
console_command = "php /var/www/html/artisan tinker"

[build]
  [build.args]
    NODE_VERSION = "18"
    PHP_VERSION = "8.1"

[env]
  APP_ENV = "production"
  APP_NAME = "chh-team3-bclc-app"
  DB_CONNECTION = "pgsql"
  DB_DATABASE = "postgres"
  DB_HOST = "db.qvckjanpxnizidkuzcjp.supabase.co"
  DB_PASSWORD = "chh-team3-db"
  DB_PORT = "5432"
  DB_USERNAME = "postgres"
  LOG_CHANNEL = "stderr"
  LOG_LEVEL = "info"
  LOG_STDERR_FORMATTER = "Monolog\\Formatter\\JsonFormatter"
  SESSION_DRIVER = "cookie"
  SESSION_SECURE_COOKIE = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
